apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-377628708
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-817091220
  resourceQuotas: {}
