apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-928301105
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-708870579
  resourceQuotas: {}
