apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-661851105
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ocicluster-241120873
  resourceQuotas: {}
