apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-499959697
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-aws-rhel10-809368606
  resourceQuotas: {}
