apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-468705896
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-hacluster-320523963
  resourceQuotas: {}
