apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-566494871
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-609467017
  resourceQuotas: {}
