apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    a1: v3
    a2: v4
  name: namespacerauto-250134896
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: automation-cluster-boot-onprem-rauto-7357
  resourceQuotas: {}
