apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-18284341
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-hacluster-844282448
  resourceQuotas: {}
