apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-67637664
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-901352551
  resourceQuotas: {}
