apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-74906
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-cm-886916234
  resourceQuotas: {}
