apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-861456877
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-93927932
  resourceQuotas: {}
