apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-63479688
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ocicluster-500973726
  resourceQuotas: {}
