apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-651740665
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ocialmalinux-506324752
  resourceQuotas: {}
