apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-976735831
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-200958443
  resourceQuotas: {}
