apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-415411734
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-378662713
  resourceQuotas: {}
