apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-535987523
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-116760493
  resourceQuotas: {}
