apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-256875336
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ocialmalinux-580467727
  resourceQuotas: {}
