apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-790066253
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-917234483
  resourceQuotas: {}
