apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-724286180
  project: defaultproject
spec:
  limitRange: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ocirocky-5975420
  resourceQuotas: {}
