apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-301015163
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-ha-ocicluster-403364458
  resourceQuotas: {}
