apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: namespace-651862198
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: rauto-hacluster-601700875
  resourceQuotas: {}
