apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns-275998
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: automation-cluster-boot-onprem-rauto-7357
  resourceQuotas: {}
