apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: ns-550171901
  project: defaultproject
spec:
  limitRange: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: eks-cbp-550171901
  resourceQuotas: {}
