apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rep-drift-action: deny
  labels:
    kubernetes.io/metadata.name: rauto-ns-622256456
    name: rauto-ns-622256456
    rep-drift-reconcillation: enabled
    rep-organization: 7w2lnkp
    rep-partner: pd270k4
    rep-project: rx28oml
  name: rauto-ns-622256456
  project: defaultproject
spec:
  namespaceMeshPolicyParams: {}
  resourceQuotas: {}
