apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: simhans
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: ubuntu-simha
    - key: rafay.dev/clusterName
      value: simha-mks
  resourceQuotas: {}
