apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: testns
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
  resourceQuotas: {}
