apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: opa
  project: defaultproject
spec:
  base:
    name: default
    version: 4.0.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook: {}
  opaPolicy:
    opaPolicy:
    - name: policy-restricted
      version: version-1773247316
    - name: policy-privileged
      version: version-1773247316
    profile:
      name: default
      version: latest
  type: custom
  version: v1
  versionState: active
