apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rauto-bp-490979727
  project: defaultproject
spec:
  base:
    name: minimal
    version: 4.0.0
  componentsCriticality:
  - name: rauto-successful-addon-490979727
  customAddons:
  - name: rauto-successful-addon-490979727
    version: v1
  defaultAddons:
    disableAwsNodeTerminationHandler: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: successful
  versionState: active
